#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin

build_binary () {
    local BINARY="$1"
    local PKG_PATH="$2"

    CGO_ENABLED=0 go build -o "bin/${BINARY}" "${PKG_PATH}"
}

build_binary "harvester-auth" "."
